apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: rails-kube-app
spec:
  ports:
    - port: 6379
  selector:
    app: rails-kube-app
    tier: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector: 
    app: rails-kube-app
    tier: redis
  template:
    metadata:
      name: redis
      labels:
        app: rails-kube-app
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
